# ===============================
# PROD ENVIRONMENT
# ===============================
server.port=${SERVER_PORT:8778}

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.sql.init.mode=${SQL_INIT_MODE:never}

logging.level.root=INFO
logging.level.com.innervix.model3d=INFO
logging.level.org.apache.ibatis=WARN

app.upload-dir=${APP_UPLOAD_DIR:/opt/model-3d/upload-files}
app.security.enabled=${APP_SECURITY_ENABLED:true}
