# ===============================
# LOCAL ENVIRONMENT
# ===============================
server.port=${SERVER_PORT:8800}

spring.datasource.url=${DB_URL:jdbc:mariadb://127.0.0.1:3306/model_3d?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:admin}

spring.sql.init.mode=always

logging.level.root=INFO
logging.level.com.innervix.model3d=DEBUG
logging.level.com.innervix.model3d.model=DEBUG
logging.level.com.innervix.model3d.animation=DEBUG
logging.level.org.apache.ibatis=DEBUG

app.upload-dir=${APP_UPLOAD_DIR:upload-files}
app.security.enabled=${APP_SECURITY_ENABLED:false}
