# ===============================
# DEV ENVIRONMENT
# ===============================
server.port=${SERVER_PORT:8800}

spring.datasource.url=${DB_URL:jdbc:mariadb://127.0.0.1:3306/model_3d_dev?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8}
spring.datasource.username=${DB_USERNAME:model3d}
spring.datasource.password=${DB_PASSWORD:model3d}

spring.sql.init.mode=${SQL_INIT_MODE:always}

logging.level.root=INFO
logging.level.com.innervix.model3d=DEBUG
logging.level.org.apache.ibatis=DEBUG

app.upload-dir=${APP_UPLOAD_DIR:upload-files}
app.security.enabled=${APP_SECURITY_ENABLED:true}
