# ===============================
# DEV ENVIRONMENT
# ===============================
server.port=${SERVER_PORT:8778}

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=${DB_URL:jdbc:sqlite:./model3d-local.sqlite}
spring.datasource.username=
spring.datasource.password=

spring.sql.init.mode=${SQL_INIT_MODE:always}
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys=ON

logging.level.root=INFO
logging.level.com.innervix.model3d=DEBUG
logging.level.com.innervix.model3d.model=DEBUG
logging.level.com.innervix.model3d.animation=DEBUG
logging.level.org.apache.ibatis=DEBUG

app.upload-dir=${APP_UPLOAD_DIR:upload-files}
app.security.enabled=${APP_SECURITY_ENABLED:true}
